services:
  - type: web
    name: chatbox-app
    env: node
    plan: free
    repo: https://github.com/snehamol/chatBox
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VITE_API_BASE_URL
        value: https://chatbox-app.onrender.com/api
    autoDeploy: true
